"""initial tables

Revision ID: d458c17fa498
Revises: 
Create Date: 2026-05-21 12:46:22.990180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd458c17fa498'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('SEV1', 'SEV2', 'SEV3', 'SEV4', name='severity'), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DEDUPLICATED', 'ROUTED', 'RESOLVED', name='alertstatus'), nullable=True),
    sa.Column('routed_to', sa.String(), nullable=True),
    sa.Column('is_deduplicated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_fingerprint'), 'alerts', ['fingerprint'], unique=False)
    op.create_table('escalation_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('wait_seconds', sa.Integer(), nullable=True),
    sa.Column('notify_channel', sa.String(), nullable=False),
    sa.Column('notify_target', sa.String(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('match_service', sa.String(), nullable=True),
    sa.Column('match_team', sa.String(), nullable=True),
    sa.Column('match_severity', sa.String(), nullable=True),
    sa.Column('route_to', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_rules')
    op.drop_table('escalation_policies')
    op.drop_index(op.f('ix_alerts_fingerprint'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
